quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
# Non-blocking (App Logic)
quarkus.datasource.reactive.url=postgresql://${DB_HOST}:${DB_HOST_PORT:5432}/${DB_NAME}
quarkus.datasource.reactive.max-size=20
# Blocking (Flyway Migrations)
quarkus.datasource.jdbc.url=jdbc:${quarkus.datasource.reactive.url}
# --- Flyway Configuration ---
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
# --- 2026 Performance Features ---
quarkus.package.jar.tree-shake.mode=classes