quarkus.profile=dev
quarkus.datasource.db-kind=postgresql
# --- Flyway Configuration ---
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
# --- Web API Configuration ---
quarkus.http.root-path=/api
# This forces all /q/ endpoints to ignore the /api prefix and stay at the root!
quarkus.http.non-application-root-path=/q
