quarkus.profile=dev

%prod.quarkus.datasource.username=${POSTGRES_USER}
%prod.quarkus.datasource.password=${POSTGRES_PASSWORD}
# Non-blocking (App Logic)
%prod.quarkus.datasource.reactive.url=postgresql://${DB_HOST}:${DB_HOST_PORT:5432}/${DB_NAME}
%prod.quarkus.datasource.reactive.max-size=20
# Blocking (Flyway Migrations)
%prod.quarkus.datasource.jdbc.url=jdbc:${quarkus.datasource.reactive.url}
# --- 2026 Performance Features ---
%prod.quarkus.package.jar.tree-shake.mode=classes

quarkus.datasource.db-kind=postgresql
# --- Flyway Configuration ---
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
# --- Web API Configuration ---
quarkus.http.root-path=/api
# This forces all /q/ endpoints to ignore the /api prefix and stay at the root!
quarkus.http.non-application-root-path=/q
